#!/usr/bin/env bash

buildpack_dir="${BUILDPACK_DIR:-"$( pwd )"}"


suite() {
    # Load tests from the following files:
    source "${buildpack_dir}/test/unit"
}

# Load shUnit2 (runs the tests)
source "${buildpack_dir}/test/shunit2"
