#!/usr/bin/env bash

buildpack_dir="${BUILDPACK_DIR:-"$( pwd )"}"


testEquality() {
    assertEquals 1 1
}

testPartyLikeItIs1999() {
    year="$( date "+%Y" )"

    assertEquals "It's not 1999 :-(" "1999" "${year}"
}


# Load shUnit2
source "${buildpack_dir}/test/shunit2"
